Linear layout algo for widgets
EreliaStudio/Sparkle pull request #7
Opened 2024-02-23 10:37 UTC by joackimdb

2024-02-23 10:38 UTC, EreliaStudio commented
There is a list of documentation error you need to fix before merging this PullRequest :


- Sparkle/src/widget/spk_box_constraints.hpp:7
     Compound spk::widget::BoxConstraints is not documented.



- Sparkle/src/widget/spk_basic_widgets.hpp:229
     Compound spk::widget::Center is not documented.



- Sparkle/src/widget/spk_basic_widgets.hpp:13
     Compound spk::widget::ColoredBox is not documented.



- Sparkle/src/widget/spk_basic_widgets.hpp:165
     Compound spk::widget::Column is not documented.



- Sparkle/src/widget/spk_basic_widgets.hpp:168
     Compound spk::widget::Column::Config is not documented.



- Sparkle/src/widget/spk_basic_widgets.hpp:97
     Compound spk::widget::Padding::Config is not documented.



- Sparkle/src/widget/spk_basic_widgets.hpp:197
     Compound spk::widget::Row is not documented.



- Sparkle/src/widget/spk_basic_widgets.hpp:200
     Compound spk::widget::Row::Config is not documented.



- Sparkle/src/widget/spk_widget.hpp:231
     Compound spk::widget::SingleChildWidget is not documented.



- Sparkle/src/widget/spk_text_button.hpp:9
     Compound spk::widget::TextButton is not documented.



- Sparkle/src/widget/spk_text_label.hpp:13
     Compound spk::widget::TextLabel is not documented.



- Sparkle/src/widget/components/spk_colored_box.hpp:8
     Compound spk::widget::components::ColoredBox is not documented.



- Sparkle/src/widget/spk_widget.hpp:129
     Member render() (function) of class spk::widget::IWidget is not documented.



- Sparkle/src/widget/spk_widget.hpp:130
     Member update() (function) of class spk::widget::IWidget is not documented.



- Sparkle/src/widget/spk_widget.hpp:228
     Member id() const (function) of class spk::widget::IWidget is not documented.



- Sparkle/src/math/spk_matrix4x4.hpp:59
     Member Matrix4x4(float aa, float ab, float ac, float ad, float ba, float bb, float bc, float bd, float ca, float cb, float cc, float cd, float da, float db, float dc, float dd) (function) of class spk::Matrix4x4 is not documented.



- Sparkle/src/math/spk_matrix4x4.hpp:61
     Member operator*(const IVector3< float > &v) const (function) of class spk::Matrix4x4 is not documented.



- Sparkle/src/math/spk_matrix4x4.hpp:70
     Member operator*(const IVector2< float > &v) const (function) of class spk::Matrix4x4 is not documented.



- Sparkle/src/math/spk_matrix4x4.hpp:84
     Member operator+(const Matrix4x4 &other) const (function) of class spk::Matrix4x4 is not documented.



- Sparkle/src/math/spk_matrix4x4.hpp:86
     Member zero() (function) of class spk::Matrix4x4 is not documented.



- Sparkle/src/widget/spk_basic_widgets.hpp:22
     Member ColoredBox(const std::string &name, const spk::Color &color, IWidget *parent) (function) of class spk::widget::ColoredBox is not documented.



- Sparkle/src/widget/spk_basic_widgets.hpp:24
     Member ColoredBox(const spk::Color &color, IWidget *parent) (function) of class spk::widget::ColoredBox is not documented.



- Sparkle/src/widget/spk_widget.hpp:234
     Member SingleChildWidget(const std::string &p_name, IWidget *p_parent=nullptr) (function) of class spk::widget::SingleChildWidget is not documented.



- Sparkle/src/widget/spk_widget.hpp:239
     Member child() (function) of class spk::widget::SingleChildWidget is not documented.



- Sparkle/src/widget/spk_widget.hpp:129
     Member render() (function) of class spk::widget::IWidget is not documented.



- Sparkle/src/widget/spk_widget.hpp:130
     Member update() (function) of class spk::widget::IWidget is not documented.



- Sparkle/src/widget/spk_widget.hpp:228
     Member id() const (function) of class spk::widget::IWidget is not documented.



- Sparkle/src/widget/spk_basic_widgets.hpp:35
     Member Builder (typedef) of class spk::widget::LayoutBuilder is not documented.



- Sparkle/src/widget/spk_basic_widgets.hpp:36
     Member LayoutBuilder(const Builder &p_builder, IWidget *p_parent) (function) of class spk::widget::LayoutBuilder is not documented.



- Sparkle/src/widget/spk_widget.hpp:129
     Member render() (function) of class spk::widget::IWidget is not documented.



- Sparkle/src/widget/spk_widget.hpp:130
     Member update() (function) of class spk::widget::IWidget is not documented.



- Sparkle/src/widget/spk_widget.hpp:228
     Member id() const (function) of class spk::widget::IWidget is not documented.



- Sparkle/src/widget/spk_basic_widgets.hpp:57
     Member SizedBox(const Vector2 &p_size, IWidget *p_parent) (function) of class spk::widget::SizedBox is not documented.



- Sparkle/src/widget/spk_basic_widgets.hpp:63
     Member size() const (function) of class spk::widget::SizedBox is not documented.



- Sparkle/src/widget/spk_widget.hpp:234
     Member SingleChildWidget(const std::string &p_name, IWidget *p_parent=nullptr) (function) of class spk::widget::SingleChildWidget is not documented.



- Sparkle/src/widget/spk_widget.hpp:239
     Member child() (function) of class spk::widget::SingleChildWidget is not documented.



- Sparkle/src/widget/spk_widget.hpp:129
     Member render() (function) of class spk::widget::IWidget is not documented.



- Sparkle/src/widget/spk_widget.hpp:130
     Member update() (function) of class spk::widget::IWidget is not documented.



- Sparkle/src/widget/spk_widget.hpp:228
     Member id() const (function) of class spk::widget::IWidget is not documented.



- Sparkle/src/widget/spk_basic_widgets.hpp:77
     Member FractionallySizedBox(float p_horizontal, float p_vertical, IWidget *p_parent) (function) of class spk::widget::FractionallySizedBox is not documented.



- Sparkle/src/widget/spk_widget.hpp:234
     Member SingleChildWidget(const std::string &p_name, IWidget *p_parent=nullptr) (function) of class spk::widget::SingleChildWidget is not documented.



- Sparkle/src/widget/spk_widget.hpp:239
     Member child() (function) of class spk::widget::SingleChildWidget is not documented.



- Sparkle/src/widget/spk_widget.hpp:129
     Member render() (function) of class spk::widget::IWidget is not documented.



- Sparkle/src/widget/spk_widget.hpp:130
     Member update() (function) of class spk::widget::IWidget is not documented.



- Sparkle/src/widget/spk_widget.hpp:228
     Member id() const (function) of class spk::widget::IWidget is not documented.



- Sparkle/src/widget/spk_basic_widgets.hpp:105
     Member Padding(const Config &p_config, IWidget *p_parent) (function) of class spk::widget::Padding is not documented.



- Sparkle/src/widget/spk_widget.hpp:234
     Member SingleChildWidget(const std::string &p_name, IWidget *p_parent=nullptr) (function) of class spk::widget::SingleChildWidget is not documented.



- Sparkle/src/widget/spk_widget.hpp:239
     Member child() (function) of class spk::widget::SingleChildWidget is not documented.



- Sparkle/src/widget/spk_widget.hpp:129
     Member render() (function) of class spk::widget::IWidget is not documented.



- Sparkle/src/widget/spk_widget.hpp:130
     Member update() (function) of class spk::widget::IWidget is not documented.



- Sparkle/src/widget/spk_widget.hpp:228
     Member id() const (function) of class spk::widget::IWidget is not documented.



- Sparkle/src/widget/spk_basic_widgets.hpp:111
     Member symmetric(float p_horizontal, float p_vertical, IWidget *p_parent) (function) of class spk::widget::Padding is not documented.



- Sparkle/src/widget/spk_basic_widgets.hpp:112
     Member all(float p_value, IWidget *p_parent) (function) of class spk::widget::Padding is not documented.



- Sparkle/src/widget/spk_basic_widgets.hpp:99
     Member left (variable) of struct spk::widget::Padding::Config is not documented.



- Sparkle/src/widget/spk_basic_widgets.hpp:100
     Member right (variable) of struct spk::widget::Padding::Config is not documented.



- Sparkle/src/widget/spk_basic_widgets.hpp:101
     Member top (variable) of struct spk::widget::Padding::Config is not documented.



- Sparkle/src/widget/spk_basic_widgets.hpp:102
     Memb [...]

2024-02-23 21:46 UTC, EreliaStudio commented
There is a list of documentation error you need to fix before merging this PullRequest :


- Sparkle/src/widget/spk_text_label.hpp:14
     missing argument after '\class'.



- Sparkle/src/graphics/spk_color.hpp:87
     Compound spk::Colors is not documented.



- Sparkle/src/widget/spk_box_constraints.hpp:7
     Compound spk::widget::BoxConstraints is not documented.



- Sparkle/src/widget/spk_text_button.hpp:9
     Compound spk::widget::TextButton is not documented.



- Sparkle/src/widget/spk_text_label.hpp:17
     Compound spk::widget::TextLabel is not documented.



- Sparkle/src/widget/components/spk_colored_box.hpp:8
     Compound spk::widget::components::ColoredBox is not documented.



- Sparkle/src/widget/spk_widget.hpp:233
     Member id() const (function) of class spk::widget::IWidget is not documented.



- Sparkle/src/graphics/spk_color.hpp:100
     Member values() (function) of class spk::Colors is not documented.



- Sparkle/src/graphics/spk_color.hpp:90
     Member red (variable) of class spk::Colors is not documented.



- Sparkle/src/graphics/spk_color.hpp:91
     Member blue (variable) of class spk::Colors is not documented.



- Sparkle/src/graphics/spk_color.hpp:92
     Member green (variable) of class spk::Colors is not documented.



- Sparkle/src/graphics/spk_color.hpp:93
     Member yellow (variable) of class spk::Colors is not documented.



- Sparkle/src/graphics/spk_color.hpp:94
     Member purple (variable) of class spk::Colors is not documented.



- Sparkle/src/graphics/spk_color.hpp:95
     Member cyan (variable) of class spk::Colors is not documented.



- Sparkle/src/graphics/spk_color.hpp:96
     Member orange (variable) of class spk::Colors is not documented.



- Sparkle/src/graphics/spk_color.hpp:97
     Member magenta (variable) of class spk::Colors is not documented.



- Sparkle/src/graphics/spk_color.hpp:98
     Member pink (variable) of class spk::Colors is not documented.



- Sparkle/src/graphics/spk_color.hpp:102
     Member black (variable) of class spk::Colors is not documented.



- Sparkle/src/graphics/spk_color.hpp:103
     Member white (variable) of class spk::Colors is not documented.



- Sparkle/src/graphics/spk_color.hpp:104
     Member grey (variable) of class spk::Colors is not documented.



- Sparkle/src/math/spk_matrix4x4.hpp:59
     Member Matrix4x4(float aa, float ab, float ac, float ad, float ba, float bb, float bc, float bd, float ca, float cb, float cc, float cd, float da, float db, float dc, float dd) (function) of class spk::Matrix4x4 is not documented.



- Sparkle/src/math/spk_matrix4x4.hpp:61
     Member operator*(const IVector3< float > &v) const (function) of class spk::Matrix4x4 is not documented.



- Sparkle/src/math/spk_matrix4x4.hpp:70
     Member operator*(const IVector2< float > &v) const (function) of class spk::Matrix4x4 is not documented.



- Sparkle/src/math/spk_matrix4x4.hpp:84
     Member operator+(const Matrix4x4 &other) const (function) of class spk::Matrix4x4 is not documented.



- Sparkle/src/math/spk_matrix4x4.hpp:86
     Member zero() (function) of class spk::Matrix4x4 is not documented.



- Sparkle/src/widget/spk_widget.hpp:244
     Member SingleChildWidget(const std::string &p_name, IWidget *p_parent=nullptr) (function) of class spk::widget::SingleChildWidget is not documented.



- Sparkle/src/widget/spk_widget.hpp:233
     Member id() const (function) of class spk::widget::IWidget is not documented.



- Sparkle/src/widget/spk_widget.hpp:244
     Member SingleChildWidget(const std::string &p_name, IWidget *p_parent=nullptr) (function) of class spk::widget::SingleChildWidget is not documented.



- Sparkle/src/widget/spk_widget.hpp:233
     Member id() const (function) of class spk::widget::IWidget is not documented.



- Sparkle/src/widget/spk_basic_widgets.hpp:91
     Member size() const (function) of class spk::widget::SizedBox is not documented.



- Sparkle/src/widget/spk_widget.hpp:244
     Member SingleChildWidget(const std::string &p_name, IWidget *p_parent=nullptr) (function) of class spk::widget::SingleChildWidget is not documented.



- Sparkle/src/widget/spk_widget.hpp:233
     Member id() const (function) of class spk::widget::IWidget is not documented.



- Sparkle/src/widget/spk_widget.hpp:244
     Member SingleChildWidget(const std::string &p_name, IWidget *p_parent=nullptr) (function) of class spk::widget::SingleChildWidget is not documented.



- Sparkle/src/widget/spk_widget.hpp:233
     Member id() const (function) of class spk::widget::IWidget is not documented.



- Sparkle/src/widget/spk_widget.hpp:244
     Member SingleChildWidget(const std::string &p_name, IWidget *p_parent=nullptr) (function) of class spk::widget::SingleChildWidget is not documented.



- Sparkle/src/widget/spk_widget.hpp:233
     Member id() const (function) of class spk::widget::IWidget is not documented.



- Sparkle/src/widget/spk_basic_widgets.hpp:137
     Member left (variable) of struct spk::widget::Padding::Config is not documented.



- Sparkle/src/widget/spk_basic_widgets.hpp:138
     Member right (variable) of struct spk::widget::Padding::Config is not documented.



- Sparkle/src/widget/spk_basic_widgets.hpp:139
     Member top (variable) of struct spk::widget::Padding::Config is not documented.



- Sparkle/src/widget/spk_basic_widgets.hpp:140
     Member bottom (variable) of struct spk::widget::Padding::Config is not documented.



- Sparkle/src/widget/spk_widget.hpp:244
     Member SingleChildWidget(const std::string &p_name, IWidget *p_parent=nullptr) (function) of class spk::widget::SingleChildWidget is not documented.



- Sparkle/src/widget/spk_widget.hpp:233
     Member id() const (function) of class spk::widget::IWidget is not documented.



- Sparkle/src/widget/spk_widget.hpp:233
     Member id() const (function) of class spk::widget::IWidget is not documented.



- Sparkle/src/widget/spk_basic_widgets.hpp:261
     Member mainAxisAlignment (variable) of struct spk::widget::Column::Config is not documented.



- Sparkle/src/widget/spk_basic_widgets.hpp:262
     Member crossAxisAlignment (variable) of struct spk::widget::Column::Config is not documented.



- Sparkle/src/widget/spk_widget.hpp:233
     Member id() const (function) of class spk::widget::IWidget is not documented.



- Sparkle/src/widget/spk_basic_widgets.hpp:309
     Member mainAxisAlignment (variable) of struct spk::widget::Row::Config is not documented.



- Sparkle/src/widget/spk_basic_widgets.hpp:310
     Member crossAxisAlignment (variable) of struct spk::widget::Row::Config is not documented.



- Sparkle/src/widget/spk_widget.hpp:244
     Member SingleChildWidget(const std::string &p_name, IWidget *p_parent=nullptr) (function) of class spk::widget::SingleChildWidget is not documented.



- Sparkle/src/widget/spk_widget.hpp:233
     Member id() const (function) of class spk::widget::IWidget is not documented.



- Sparkle/src/widget/spk_box_constraints.hpp:12
     Member BoxConstraints(const Vector2 &p_min, const Vector2 &p_max) (function) of struct spk::widget::BoxConstraints is not documented.



- Sparkle/src/widget/spk_box_constraints.hpp:9
     Member min (variable) of struct spk::widget::BoxConstraints is not documented.



- Sparkle/src/widget/spk_box_constraints.hpp:10
     Member max (variable) of struct spk::widget::BoxConstraints is not documented.



- Sparkle/src/widget/spk_widget.hpp:233
     Member id() const (function) of class spk::widget::IWidget is not documented.



- Sparkle/src/widget/spk_pointer_detector.hpp:19
     Member Callback (typedef) of class spk::widget::PointerDetector is not documented.



- Sparkle/src/widget/spk_pointer_detector.hpp:14
     Member PointerDetector(IWidget *p_parent) (function) of class spk::widget::PointerDetector is not documented.



- Sparkle/src/widget/spk_pointer_detector.hpp:21
     Member setOnPressed(const Callback &p_onPressed) (function) of class spk::widget::PointerDetector is not documented.



- Sparkle [...]

2024-02-23 22:12 UTC, EreliaStudio commented
There is a list of documentation error you need to fix before merging this PullRequest :


- Sparkle/src/widget/spk_text_label.hpp:14
     missing argument after '\class'.



- Sparkle/src/graphics/spk_color.hpp:87
     Compound spk::Colors is not documented.



- Sparkle/src/widget/spk_box_constraints.hpp:7
     Compound spk::widget::BoxConstraints is not documented.



- Sparkle/src/widget/spk_text_button.hpp:9
     Compound spk::widget::TextButton is not documented.



- Sparkle/src/widget/spk_text_label.hpp:17
     Compound spk::widget::TextLabel is not documented.



- Sparkle/src/widget/components/spk_colored_box.hpp:8
     Compound spk::widget::components::ColoredBox is not documented.



- Sparkle/src/graphics/spk_color.hpp:100
     Member values() (function) of class spk::Colors is not documented.



- Sparkle/src/graphics/spk_color.hpp:90
     Member red (variable) of class spk::Colors is not documented.



- Sparkle/src/graphics/spk_color.hpp:91
     Member blue (variable) of class spk::Colors is not documented.



- Sparkle/src/graphics/spk_color.hpp:92
     Member green (variable) of class spk::Colors is not documented.



- Sparkle/src/graphics/spk_color.hpp:93
     Member yellow (variable) of class spk::Colors is not documented.



- Sparkle/src/graphics/spk_color.hpp:94
     Member purple (variable) of class spk::Colors is not documented.



- Sparkle/src/graphics/spk_color.hpp:95
     Member cyan (variable) of class spk::Colors is not documented.



- Sparkle/src/graphics/spk_color.hpp:96
     Member orange (variable) of class spk::Colors is not documented.



- Sparkle/src/graphics/spk_color.hpp:97
     Member magenta (variable) of class spk::Colors is not documented.



- Sparkle/src/graphics/spk_color.hpp:98
     Member pink (variable) of class spk::Colors is not documented.



- Sparkle/src/graphics/spk_color.hpp:102
     Member black (variable) of class spk::Colors is not documented.



- Sparkle/src/graphics/spk_color.hpp:103
     Member white (variable) of class spk::Colors is not documented.



- Sparkle/src/graphics/spk_color.hpp:104
     Member grey (variable) of class spk::Colors is not documented.



- Sparkle/src/math/spk_matrix4x4.hpp:59
     Member Matrix4x4(float aa, float ab, float ac, float ad, float ba, float bb, float bc, float bd, float ca, float cb, float cc, float cd, float da, float db, float dc, float dd) (function) of class spk::Matrix4x4 is not documented.



- Sparkle/src/math/spk_matrix4x4.hpp:61
     Member operator*(const IVector3< float > &v) const (function) of class spk::Matrix4x4 is not documented.



- Sparkle/src/math/spk_matrix4x4.hpp:70
     Member operator*(const IVector2< float > &v) const (function) of class spk::Matrix4x4 is not documented.



- Sparkle/src/math/spk_matrix4x4.hpp:84
     Member operator+(const Matrix4x4 &other) const (function) of class spk::Matrix4x4 is not documented.



- Sparkle/src/math/spk_matrix4x4.hpp:86
     Member zero() (function) of class spk::Matrix4x4 is not documented.



- Sparkle/src/widget/spk_widget.hpp:247
     Member SingleChildWidget(const std::string &p_name, IWidget *p_parent=nullptr) (function) of class spk::widget::SingleChildWidget is not documented.



- Sparkle/src/widget/spk_widget.hpp:247
     Member SingleChildWidget(const std::string &p_name, IWidget *p_parent=nullptr) (function) of class spk::widget::SingleChildWidget is not documented.



- Sparkle/src/widget/spk_basic_widgets.hpp:91
     Member size() const (function) of class spk::widget::SizedBox is not documented.



- Sparkle/src/widget/spk_widget.hpp:247
     Member SingleChildWidget(const std::string &p_name, IWidget *p_parent=nullptr) (function) of class spk::widget::SingleChildWidget is not documented.



- Sparkle/src/widget/spk_widget.hpp:247
     Member SingleChildWidget(const std::string &p_name, IWidget *p_parent=nullptr) (function) of class spk::widget::SingleChildWidget is not documented.



- Sparkle/src/widget/spk_widget.hpp:247
     Member SingleChildWidget(const std::string &p_name, IWidget *p_parent=nullptr) (function) of class spk::widget::SingleChildWidget is not documented.



- Sparkle/src/widget/spk_basic_widgets.hpp:137
     Member left (variable) of struct spk::widget::Padding::Config is not documented.



- Sparkle/src/widget/spk_basic_widgets.hpp:138
     Member right (variable) of struct spk::widget::Padding::Config is not documented.



- Sparkle/src/widget/spk_basic_widgets.hpp:139
     Member top (variable) of struct spk::widget::Padding::Config is not documented.



- Sparkle/src/widget/spk_basic_widgets.hpp:140
     Member bottom (variable) of struct spk::widget::Padding::Config is not documented.



- Sparkle/src/widget/spk_widget.hpp:247
     Member SingleChildWidget(const std::string &p_name, IWidget *p_parent=nullptr) (function) of class spk::widget::SingleChildWidget is not documented.



- Sparkle/src/widget/spk_basic_widgets.hpp:261
     Member mainAxisAlignment (variable) of struct spk::widget::Column::Config is not documented.



- Sparkle/src/widget/spk_basic_widgets.hpp:262
     Member crossAxisAlignment (variable) of struct spk::widget::Column::Config is not documented.



- Sparkle/src/widget/spk_basic_widgets.hpp:309
     Member mainAxisAlignment (variable) of struct spk::widget::Row::Config is not documented.



- Sparkle/src/widget/spk_basic_widgets.hpp:310
     Member crossAxisAlignment (variable) of struct spk::widget::Row::Config is not documented.



- Sparkle/src/widget/spk_widget.hpp:247
     Member SingleChildWidget(const std::string &p_name, IWidget *p_parent=nullptr) (function) of class spk::widget::SingleChildWidget is not documented.



- Sparkle/src/widget/spk_box_constraints.hpp:12
     Member BoxConstraints(const Vector2 &p_min, const Vector2 &p_max) (function) of struct spk::widget::BoxConstraints is not documented.



- Sparkle/src/widget/spk_box_constraints.hpp:9
     Member min (variable) of struct spk::widget::BoxConstraints is not documented.



- Sparkle/src/widget/spk_box_constraints.hpp:10
     Member max (variable) of struct spk::widget::BoxConstraints is not documented.



- Sparkle/src/widget/spk_pointer_detector.hpp:19
     Member Callback (typedef) of class spk::widget::PointerDetector is not documented.



- Sparkle/src/widget/spk_pointer_detector.hpp:14
     Member PointerDetector(IWidget *p_parent) (function) of class spk::widget::PointerDetector is not documented.



- Sparkle/src/widget/spk_pointer_detector.hpp:21
     Member setOnPressed(const Callback &p_onPressed) (function) of class spk::widget::PointerDetector is not documented.



- Sparkle/src/widget/spk_pointer_detector.hpp:22
     Member setOnReleased(const Callback &p_onReleased) (function) of class spk::widget::PointerDetector is not documented.



- Sparkle/src/widget/spk_pointer_detector.hpp:23
     Member setOnEnter(const Callback &p_onEnter) (function) of class spk::widget::PointerDetector is not documented.



- Sparkle/src/widget/spk_pointer_detector.hpp:24
     Member setOnExit(const Callback &p_onExit) (function) of class spk::widget::PointerDetector is not documented.



- Sparkle/src/widget/spk_pointer_detector.hpp:26
     Member isPressed() const (function) of class spk::widget::PointerDetector is not documented.



- Sparkle/src/widget/spk_pointer_detector.hpp:27
     Member isHovered() const (function) of class spk::widget::PointerDetector is not documented.



- Sparkle/src/widget/spk_widget.hpp:247
     Member SingleChildWidget(const std::string &p_name, IWidget *p_parent=nullptr) (function) of class spk::widget::SingleChildWidget is not documented.



- Sparkle/src/widget/spk_text_button.hpp:12
     Member Callback (typedef) of class spk::widget::TextButton is not documented.



- Sparkle/src/widget/spk_text_button.hpp:13
     Member TextButton(const std::string &p_text, const Callback &p_onPressed, spk::Font *p_font, IWidget *p_parent) (function) of class spk::widget::TextButton is not documented.



- Sparkle/src/widget/spk_wi [...]

2024-02-25 09:31 UTC, EreliaStudio commented
There is a list of documentation error you need to fix before merging this PullRequest :


- Sparkle/src/widget/spk_text_label.hpp:14
     missing argument after '\class'.



- Sparkle/src/widget/spk_text_label.hpp:17
     Compound spk::widget::TextLabel is not documented.



- Sparkle/src/widget/components/spk_colored_box.hpp:8
     Compound spk::widget::components::ColoredBox is not documented.



- Sparkle/src/graphics/spk_color.hpp:103
     Member values() (function) of class spk::Colors is not documented.



- Sparkle/src/graphics/spk_color.hpp:93
     Member red (variable) of class spk::Colors is not documented.



- Sparkle/src/graphics/spk_color.hpp:94
     Member blue (variable) of class spk::Colors is not documented.



- Sparkle/src/graphics/spk_color.hpp:95
     Member green (variable) of class spk::Colors is not documented.



- Sparkle/src/graphics/spk_color.hpp:96
     Member yellow (variable) of class spk::Colors is not documented.



- Sparkle/src/graphics/spk_color.hpp:97
     Member purple (variable) of class spk::Colors is not documented.



- Sparkle/src/graphics/spk_color.hpp:98
     Member cyan (variable) of class spk::Colors is not documented.



- Sparkle/src/graphics/spk_color.hpp:99
     Member orange (variable) of class spk::Colors is not documented.



- Sparkle/src/graphics/spk_color.hpp:100
     Member magenta (variable) of class spk::Colors is not documented.



- Sparkle/src/graphics/spk_color.hpp:101
     Member pink (variable) of class spk::Colors is not documented.



- Sparkle/src/graphics/spk_color.hpp:105
     Member black (variable) of class spk::Colors is not documented.



- Sparkle/src/graphics/spk_color.hpp:106
     Member white (variable) of class spk::Colors is not documented.



- Sparkle/src/graphics/spk_color.hpp:107
     Member grey (variable) of class spk::Colors is not documented.



- Sparkle/src/math/spk_matrix4x4.hpp:59
     Member Matrix4x4(float aa, float ab, float ac, float ad, float ba, float bb, float bc, float bd, float ca, float cb, float cc, float cd, float da, float db, float dc, float dd) (function) of class spk::Matrix4x4 is not documented.



- Sparkle/src/math/spk_matrix4x4.hpp:61
     Member operator*(const IVector3< float > &v) const (function) of class spk::Matrix4x4 is not documented.



- Sparkle/src/math/spk_matrix4x4.hpp:70
     Member operator*(const IVector2< float > &v) const (function) of class spk::Matrix4x4 is not documented.



- Sparkle/src/math/spk_matrix4x4.hpp:84
     Member operator+(const Matrix4x4 &other) const (function) of class spk::Matrix4x4 is not documented.



- Sparkle/src/math/spk_matrix4x4.hpp:86
     Member zero() (function) of class spk::Matrix4x4 is not documented.



- Sparkle/src/widget/spk_basic_widgets.hpp:91
     Member size() const (function) of class spk::widget::SizedBox is not documented.



- Sparkle/src/widget/spk_basic_widgets.hpp:157
     Member all(float p_pad) (function) of struct spk::widget::Padding::Config is not documented.



- Sparkle/src/widget/spk_basic_widgets.hpp:137
     Member left (variable) of struct spk::widget::Padding::Config is not documented.



- Sparkle/src/widget/spk_basic_widgets.hpp:138
     Member right (variable) of struct spk::widget::Padding::Config is not documented.



- Sparkle/src/widget/spk_basic_widgets.hpp:139
     Member top (variable) of struct spk::widget::Padding::Config is not documented.



- Sparkle/src/widget/spk_basic_widgets.hpp:140
     Member bottom (variable) of struct spk::widget::Padding::Config is not documented.



- Sparkle/src/widget/spk_basic_widgets.hpp:248
     Member mainAxisAlignment (variable) of struct spk::widget::Column::Config is not documented.



- Sparkle/src/widget/spk_basic_widgets.hpp:249
     Member crossAxisAlignment (variable) of struct spk::widget::Column::Config is not documented.



- Sparkle/src/widget/spk_basic_widgets.hpp:296
     Member mainAxisAlignment (variable) of struct spk::widget::Row::Config is not documented.



- Sparkle/src/widget/spk_basic_widgets.hpp:297
     Member crossAxisAlignment (variable) of struct spk::widget::Row::Config is not documented.



- Sparkle/src/widget/spk_box_constraints.hpp:12
     Member min (variable) of struct spk::widget::BoxConstraints is not documented.



- Sparkle/src/widget/spk_box_constraints.hpp:13
     Member max (variable) of struct spk::widget::BoxConstraints is not documented.



- Sparkle/src/widget/components/spk_colored_box.hpp:36
     Member render() (function) of class spk::widget::components::ColoredBox is not documented.



- Sparkle/src/widget/components/spk_colored_box.hpp:38
     Member anchor() const (function) of class spk::widget::components::ColoredBox is not documented.



- Sparkle/src/widget/components/spk_colored_box.hpp:39
     Member size() const (function) of class spk::widget::components::ColoredBox is not documented.



- Sparkle/src/widget/components/spk_colored_box.hpp:41
     Member setGeometry(const Vector2 p_anchor, const Vector2 p_newSize) (function) of class spk::widget::components::ColoredBox is not documented.



- Sparkle/src/widget/components/spk_colored_box.hpp:42
     Member setDepth(float p_newDepth) (function) of class spk::widget::components::ColoredBox is not documented.



- Sparkle/src/widget/components/spk_colored_box.hpp:43
     Member setColor(const spk::Color &p_color) (function) of class spk::widget::components::ColoredBox is not documented.

2024-02-25 19:58 UTC, EreliaStudio commented
There is a list of documentation error you need to fix before merging this PullRequest :


- Sparkle/src/widget/spk_text_label.hpp:14
     missing argument after '\class'.



- Sparkle/src/widget/spk_text_label.hpp:17
     Compound spk::widget::TextLabel is not documented.



- Sparkle/src/widget/components/spk_colored_box.hpp:8
     Compound spk::widget::components::ColoredBox is not documented.



- Sparkle/src/graphics/spk_color.hpp:103
     Member values() (function) of class spk::Colors is not documented.



- Sparkle/src/graphics/spk_color.hpp:93
     Member red (variable) of class spk::Colors is not documented.



- Sparkle/src/graphics/spk_color.hpp:94
     Member blue (variable) of class spk::Colors is not documented.



- Sparkle/src/graphics/spk_color.hpp:95
     Member green (variable) of class spk::Colors is not documented.



- Sparkle/src/graphics/spk_color.hpp:96
     Member yellow (variable) of class spk::Colors is not documented.



- Sparkle/src/graphics/spk_color.hpp:97
     Member purple (variable) of class spk::Colors is not documented.



- Sparkle/src/graphics/spk_color.hpp:98
     Member cyan (variable) of class spk::Colors is not documented.



- Sparkle/src/graphics/spk_color.hpp:99
     Member orange (variable) of class spk::Colors is not documented.



- Sparkle/src/graphics/spk_color.hpp:100
     Member magenta (variable) of class spk::Colors is not documented.



- Sparkle/src/graphics/spk_color.hpp:101
     Member pink (variable) of class spk::Colors is not documented.



- Sparkle/src/graphics/spk_color.hpp:105
     Member black (variable) of class spk::Colors is not documented.



- Sparkle/src/graphics/spk_color.hpp:106
     Member white (variable) of class spk::Colors is not documented.



- Sparkle/src/graphics/spk_color.hpp:107
     Member grey (variable) of class spk::Colors is not documented.



- Sparkle/src/math/spk_matrix4x4.hpp:59
     Member Matrix4x4(float aa, float ab, float ac, float ad, float ba, float bb, float bc, float bd, float ca, float cb, float cc, float cd, float da, float db, float dc, float dd) (function) of class spk::Matrix4x4 is not documented.



- Sparkle/src/math/spk_matrix4x4.hpp:61
     Member operator*(const IVector3< float > &v) const (function) of class spk::Matrix4x4 is not documented.



- Sparkle/src/math/spk_matrix4x4.hpp:70
     Member operator*(const IVector2< float > &v) const (function) of class spk::Matrix4x4 is not documented.



- Sparkle/src/math/spk_matrix4x4.hpp:84
     Member operator+(const Matrix4x4 &other) const (function) of class spk::Matrix4x4 is not documented.



- Sparkle/src/math/spk_matrix4x4.hpp:86
     Member zero() (function) of class spk::Matrix4x4 is not documented.



- Sparkle/src/widget/spk_basic_widgets.hpp:91
     Member size() const (function) of class spk::widget::SizedBox is not documented.



- Sparkle/src/widget/spk_basic_widgets.hpp:157
     Member all(float p_pad) (function) of struct spk::widget::Padding::Config is not documented.



- Sparkle/src/widget/spk_basic_widgets.hpp:137
     Member left (variable) of struct spk::widget::Padding::Config is not documented.



- Sparkle/src/widget/spk_basic_widgets.hpp:138
     Member right (variable) of struct spk::widget::Padding::Config is not documented.



- Sparkle/src/widget/spk_basic_widgets.hpp:139
     Member top (variable) of struct spk::widget::Padding::Config is not documented.



- Sparkle/src/widget/spk_basic_widgets.hpp:140
     Member bottom (variable) of struct spk::widget::Padding::Config is not documented.



- Sparkle/src/widget/spk_basic_widgets.hpp:248
     Member mainAxisAlignment (variable) of struct spk::widget::Column::Config is not documented.



- Sparkle/src/widget/spk_basic_widgets.hpp:249
     Member crossAxisAlignment (variable) of struct spk::widget::Column::Config is not documented.



- Sparkle/src/widget/spk_basic_widgets.hpp:296
     Member mainAxisAlignment (variable) of struct spk::widget::Row::Config is not documented.



- Sparkle/src/widget/spk_basic_widgets.hpp:297
     Member crossAxisAlignment (variable) of struct spk::widget::Row::Config is not documented.



- Sparkle/src/widget/spk_box_constraints.hpp:12
     Member min (variable) of struct spk::widget::BoxConstraints is not documented.



- Sparkle/src/widget/spk_box_constraints.hpp:13
     Member max (variable) of struct spk::widget::BoxConstraints is not documented.



- Sparkle/src/widget/components/spk_colored_box.hpp:36
     Member render() (function) of class spk::widget::components::ColoredBox is not documented.



- Sparkle/src/widget/components/spk_colored_box.hpp:38
     Member anchor() const (function) of class spk::widget::components::ColoredBox is not documented.



- Sparkle/src/widget/components/spk_colored_box.hpp:39
     Member size() const (function) of class spk::widget::components::ColoredBox is not documented.



- Sparkle/src/widget/components/spk_colored_box.hpp:41
     Member setGeometry(const Vector2 p_anchor, const Vector2 p_newSize) (function) of class spk::widget::components::ColoredBox is not documented.



- Sparkle/src/widget/components/spk_colored_box.hpp:42
     Member setDepth(float p_newDepth) (function) of class spk::widget::components::ColoredBox is not documented.



- Sparkle/src/widget/components/spk_colored_box.hpp:43
     Member setColor(const spk::Color &p_color) (function) of class spk::widget::components::ColoredBox is not documented.

2024-02-25 21:45 UTC, EreliaStudio commented
There is a list of documentation error you need to fix before merging this PullRequest :


- Sparkle/src/widget/spk_basic_widgets.hpp:91
     Member size() const (function) of class spk::widget::SizedBox is not documented.



- Sparkle/src/widget/spk_basic_widgets.hpp:157
     Member all(float p_pad) (function) of struct spk::widget::Padding::Config is not documented.



- Sparkle/src/widget/spk_basic_widgets.hpp:137
     Member left (variable) of struct spk::widget::Padding::Config is not documented.



- Sparkle/src/widget/spk_basic_widgets.hpp:138
     Member right (variable) of struct spk::widget::Padding::Config is not documented.



- Sparkle/src/widget/spk_basic_widgets.hpp:139
     Member top (variable) of struct spk::widget::Padding::Config is not documented.



- Sparkle/src/widget/spk_basic_widgets.hpp:140
     Member bottom (variable) of struct spk::widget::Padding::Config is not documented.



- Sparkle/src/widget/spk_basic_widgets.hpp:248
     Member mainAxisAlignment (variable) of struct spk::widget::Column::Config is not documented.



- Sparkle/src/widget/spk_basic_widgets.hpp:249
     Member crossAxisAlignment (variable) of struct spk::widget::Column::Config is not documented.



- Sparkle/src/widget/spk_basic_widgets.hpp:296
     Member mainAxisAlignment (variable) of struct spk::widget::Row::Config is not documented.



- Sparkle/src/widget/spk_basic_widgets.hpp:297
     Member crossAxisAlignment (variable) of struct spk::widget::Row::Config is not documented.



- Sparkle/src/widget/spk_box_constraints.hpp:12
     Member min (variable) of struct spk::widget::BoxConstraints is not documented.



- Sparkle/src/widget/spk_box_constraints.hpp:13
     Member max (variable) of struct spk::widget::BoxConstraints is not documented.



- Sparkle/src/widget/components/spk_colored_box.hpp:58
     argument 'p_size' of command @param is not found in the argument list of spk::widget::components::ColoredBox::setGeometry(const Vector2 p_anchor, const Vector2 p_newSize)



- Sparkle/src/widget/components/spk_colored_box.hpp:62
     The following parameter of spk::widget::components::ColoredBox::setGeometry(const Vector2 p_anchor, const Vector2 p_newSize) is not documented:
      parameter 'p_newSize'



- Sparkle/src/widget/components/spk_colored_box.hpp:58
     argument 'p_size' of command @param is not found in the argument list of spk::widget::components::ColoredBox::setGeometry(const Vector2 p_anchor, const Vector2 p_newSize)



- Sparkle/src/widget/components/spk_colored_box.hpp:62
     The following parameter of spk::widget::components::ColoredBox::setGeometry(const Vector2 p_anchor, const Vector2 p_newSize) is not documented:
      parameter 'p_newSize'

2024-02-25 22:24 UTC, EreliaStudio commented
There is a list of documentation error you need to fix before merging this PullRequest :


- Sparkle/src/widget/spk_box_constraints.hpp:12
     Member min (variable) of struct spk::widget::BoxConstraints is not documented.



- Sparkle/src/widget/spk_box_constraints.hpp:13
     Member max (variable) of struct spk::widget::BoxConstraints is not documented.



- Sparkle/src/widget/components/spk_colored_box.hpp:58
     argument 'p_size' of command @param is not found in the argument list of spk::widget::components::ColoredBox::setGeometry(const Vector2 p_anchor, const Vector2 p_newSize)



- Sparkle/src/widget/components/spk_colored_box.hpp:62
     The following parameter of spk::widget::components::ColoredBox::setGeometry(const Vector2 p_anchor, const Vector2 p_newSize) is not documented:
      parameter 'p_newSize'



- Sparkle/src/widget/components/spk_colored_box.hpp:58
     argument 'p_size' of command @param is not found in the argument list of spk::widget::components::ColoredBox::setGeometry(const Vector2 p_anchor, const Vector2 p_newSize)



- Sparkle/src/widget/components/spk_colored_box.hpp:62
     The following parameter of spk::widget::components::ColoredBox::setGeometry(const Vector2 p_anchor, const Vector2 p_newSize) is not documented:
      parameter 'p_newSize'

2024-02-26 16:37 UTC, EreliaStudio requested changes

2024-02-26 16:37 UTC, EreliaStudio commented on Sparkle/src/widget/spk_text_label.cpp
> +        IWidget::_onGeometryChange();
If realy it need to be done previously from any widget, place it just before the _onGeometryChange call, in a specific method inside IWidget, cause writing IWidget::_onGeometryChange(); everywhere isn't cool :'(

2024-02-26 16:37 UTC, EreliaStudio commented on Sparkle/src/widget/spk_text_label.cpp
> +        // TODO: need to return textlabel layout inside those constraints;
Create an issue for this, no ? To like trace what we should be looking for doing. I think i will clear up linear and create a set of stories for everything that still need to be done in sparkle.

2024-02-26 16:37 UTC, EreliaStudio commented on Sparkle/src/widget/spk_widget.cpp
> +    std::atomic_uint32_t IWidget::_nextId = 0;
Need to be keeped ? we should probably remove this

2024-02-26 16:37 UTC, EreliaStudio commented on Sparkle/src/widget/spk_widget.cpp
> +            return;
Should probably be removed

2024-02-26 16:37 UTC, EreliaStudio commented on Sparkle/src/widget/spk_widget.cpp
> +
I thought this would be located inside pointer detection widget

2024-02-26 16:37 UTC, EreliaStudio commented on Sparkle/src/widget/spk_widget.cpp
> +    }
Should probably be removed

2024-02-26 16:37 UTC, EreliaStudio commented on Sparkle/src/widget/spk_widget.cpp
> +        }
to remove and keep only the assert

2024-02-26 16:37 UTC, EreliaStudio commented on Sparkle/src/widget/spk_widget.cpp
> +    IWidget* SingleChildWidget::child()
This method should probably simply be an override of the addChild method of the IWidget. Just place it as virtual and simply do this check uppon adding a child

2024-02-26 16:37 UTC, EreliaStudio commented on Sparkle/src/widget/spk_widget.hpp
> +        uint32_t _id;
May not be needed anymore

2024-02-26 16:37 UTC, EreliaStudio commented on Sparkle/src/widget/spk_widget.hpp
> +        }
why don't return a std::unique_ptr& instead of a IWidget* ? user can try to delete the pointer, and we don't want that to happen
And create a const method, returning a const std::unique_ptr&

2024-02-26 16:37 UTC, EreliaStudio commented on Sparkle/src/widget/spk_widget.hpp
> +        virtual bool hitTest(const Vector2& p_coord);
Should probably be moved to pointer_detector widget

2024-02-26 16:37 UTC, EreliaStudio commented on Sparkle/src/widget/spk_widget.hpp
> +        uint32_t id() const;
Should probably be removed

2024-02-26 16:37 UTC, EreliaStudio commented on Sparkle/src/widget/spk_widget.hpp
> +    };
Move this into its own header file, probably

2024-02-26 16:37 UTC, EreliaStudio commented on Sparkle/src/widget/spk_widget.cpp
> +    }
Should probably move this section of code into its own cpp file

2024-02-26 22:51 UTC, EreliaStudio commented on Sparkle/src/widget/spk_widget.hpp
> +        }
After reflection, i think you're right :  we should return a TChild*. I close this ticket

2024-02-27 13:04 UTC, joackimdb commented on Sparkle/src/widget/spk_widget.cpp
> +        DLOG(name() << "#" << id() << ":" << anchor() << size() << "; depth=" << depth());
It is really useful but not needed. More than anything I think it shows that being able to explore the widget tree on a given frame is a must have feature.

2024-02-27 13:05 UTC, joackimdb commented on Sparkle/CMakeLists.txt
> +list(APPEND CMAKE_PREFIX_PATH "C:/dev/glew")
ok

2024-02-27 13:22 UTC, joackimdb commented on Sparkle/src/application/spk_application.hpp
> +                IWidget::_onGeometryChange();
ok

2024-02-27 13:22 UTC, joackimdb commented on Sparkle/src/application/spk_application.hpp
ok

2024-02-27 13:26 UTC, joackimdb commented on Sparkle/src/graphics/spk_color.hpp
> +        static const std::vector<Color>& values() { return _values; } //!< Some constant colors.
Some imaginary compilation issues. Changed it to being a static const public value.

2024-02-27 13:35 UTC, joackimdb commented on Sparkle/src/sparkle.hpp
> +}
ok

2024-02-27 14:38 UTC, joackimdb commented on Sparkle/src/widget/spk_widget.cpp
> +    std::atomic_uint32_t IWidget::_nextId = 0;
I find it useful for debug purpose. We don't always name widgets, but tracking them by id is nice.

2024-02-27 15:00 UTC, joackimdb commented on Sparkle/src/widget/spk_widget.cpp
> +
Every widget can be hit testes, the PointerDetector merely holds logic to react to its child being pointed.

2024-02-28 08:53 UTC, joackimdb commented on Sparkle/src/widget/spk_widget.cpp
> +    IWidget* SingleChildWidget::child()
This method is not meant to add a child, but rather to retrieve the single child if any. It is used by most widgets that inherit from `SingleChildWidget`.

2024-02-28 08:54 UTC, joackimdb commented on Sparkle/src/widget/spk_widget.hpp
> +        virtual bool hitTest(const Vector2& p_coord);
As discussed, it should be possible to hitTest any widget.

2024-02-28 08:56 UTC, joackimdb commented on Sparkle/src/widget/spk_widget.hpp
> +        }
Maybe a weak pointer is the way to go. We want safe access to the child, but no ownership whatsoever.

2024-02-28 08:59 UTC, joackimdb commented on Sparkle/src/widget/spk_widget.cpp
> +    }
ok

2024-02-28 08:59 UTC, joackimdb commented on Sparkle/src/widget/spk_widget.hpp
> +    };
ok

2024-02-28 09:46 UTC, EreliaStudio commented on Sparkle/src/widget/spk_widget.cpp
> +    IWidget* SingleChildWidget::child()
you misunderstund. I was talking about the nb of child verification. You should move the check to an overrided method addChild, and simply add the "child" method that return the child inside the SingleChildWidget

2024-02-28 10:26 UTC, EreliaStudio commented
There is a list of documentation error you need to fix before merging this PullRequest :


- Sparkle/src/graphics/spk_color.hpp:109
     Member values (variable) of class spk::Colors is not documented.

2024-03-05 09:40 UTC, joackimdb commented on Sparkle/src/widget/spk_widget.cpp
> +    IWidget* SingleChildWidget::child()
As discussed yesterday, I think this is unnecessary for now. It would kind of bloat the interface with duplicate code for any child-manipulation function (`addChild`, `makeChild` etc).

Checking here or in any of those methods doesn't change the temporality at which the check happens : it's all runtime, and since the `addChild` methods can be called at any point in the program, they don't offer any additional guarantee that the error can be caught earlier.

A completely different design would be necessary if we wanted to remove that check; one where IWidget doesn't expose the widget tree in the same way as it does now.

2024-03-05 09:44 UTC, joackimdb commented on Sparkle/src/widget/spk_text_label.cpp
> +        // TODO: need to return textlabel layout inside those constraints;
done #8

2024-03-05 16:17 UTC, EreliaStudio approved these changes

2024-03-05 16:18 UTC, EreliaStudio approved these changes

2024-03-05 16:22 UTC, merged